apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    # UPDATE: Set PROMETHEUS_URL as Choreo env variable
    # Choreo internal URL format: http://<project>--<component>--<endpoint>.<namespace>:9090
    url: ${PROMETHEUS_URL:-http://prometheus:9090}
    isDefault: true

  - name: loki
    type: loki
    access: proxy
    # UPDATE: Set LOKI_URL as Choreo env variable
    # Choreo internal URL format: http://<project>--<component>--<endpoint>.<namespace>:3100
    url: ${LOKI_URL:-http://loki:3100}
