schemaVersion: 1.2

endpoints:
  - name: promethius
    displayName: Promethius Dashboard
    type: REST
    service:
      basePath: /
      port: 9090
    networkVisibilities:
      - Project
      - Public